# Generated by Django 2.2.6 on 2019-10-23 02:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='timestamp of creation of campaign')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, help_text='AB test campaign code')),
                ('name', models.CharField(help_text='Name of AB test', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Description of AB test')),
                ('active', models.BooleanField(default=True, help_text='True if campaign is active')),
                ('allow_repeat', models.BooleanField(default=True, help_text='True if repeat impressions/conversions allowed by the same user')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Variant code, (i.e., A, B, C etc)', max_length=32)),
                ('name', models.CharField(help_text='Name of variant', max_length=64)),
                ('impressions', models.IntegerField(default=1, help_text='Number of times variant was shown/visited')),
                ('conversions', models.IntegerField(default=1, help_text='Number of conversions for variant')),
                ('conversion_rate', models.FloatField(default=1.0, help_text='conversions / impressions')),
                ('html_template', models.FilePathField(help_text='Path to HTML template for variant View', null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='abtest.Campaign')),
            ],
        ),
    ]
