# Generated by Django 2.2.6 on 2019-10-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abtest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='html_template',
            field=models.URLField(help_text='Path to HTML template for variant View', null=True),
        ),
    ]
