# Generated by Django 2.2.6 on 2019-10-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abtest', '0002_variant_html_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='conversion_rate',
            field=models.FloatField(default=1.0, help_text='conversions / impressions'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(help_text='Name of AB test', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='html_template',
            field=models.FilePathField(help_text='Path to HTML template for variant View', null=True),
        ),
    ]
