# Generated by Django 2.2.6 on 2019-10-18 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abtest', '0003_auto_20191017_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='active',
            field=models.BooleanField(default=True, help_text='True if campaign is active'),
        ),
    ]
