# Generated by Django 2.2.6 on 2019-10-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abtest', '0004_campaign_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='allow_repeat',
            field=models.BooleanField(default=True, help_text='True if repeat impressions/conversions allowed by the same user'),
        ),
    ]
